spring:
  cloud:
    gateway:
      routes:
#        - predicates:
#            - Path=/gateway/** #路径配置
#          filters:
#            - StripPrefix=1 #跳过前缀
#          uri: http://localhost:8080/say #路由的访问地址
        - predicates:
            - Path=/gateway/**
          id: requestratelimiter_route
          uri: http://localhost:8080/say
          filters:
            - name: RequestRateLimiter
              args:
                denyEmptyKey: true
                emptyKeyStatus: SERVICE_UNAVAILABLE
                keyResolver: '#{@ipAddressKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
server:
  port: 8088
